$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: nlp_summarization_train_test3
version: mlopsv2-july2022
build:
  path: ../../../data-science-nlp/environments/training/
