# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsv2
  postfix: 0518
  location: westus
  environment: prod
  enable_aml_computecluster: true

  # Azure DevOps 
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # IaC
  resource_group: DJMiscRG
  aml_workspace: DemoMLWorkspace
  application_insights: mlw
  key_vault: kv
  container_registry: cr
  storage_account: demomlworkspac4761520559

  # Terraform
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure
  terraform_st_resource_group: rg-test-tf-state
  terraform_st_storage_account: sttesttfstate
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
