$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: taxi-fare-training
description: Training Pipeline to train a model that predicts taxi fare price

inputs:
  input: #using local data, will crate an anonymous data asset
    type: uri_folder
    path: ../../../data/

outputs: 
  prepared_data:
  trained_model:
  predictions:
  score_report:
  deploy_flag:

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    name: prep_data
    display_name: prep-data
    code: ../../../data-science/src
    command: echo "Test"
    inputs:
      raw_data: ${{parent.inputs.input}}
    outputs:
      prepared_data: ${{parent.outputs.prepared_data}}
