$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: taxi-fare-training
description: Training Pipeline to train a model that predicts taxi fare price
inputs:
  input: #using local data, will crate an anonymous data asset
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/UI/06-24-2022_061824_UTC/demo.csv

outputs: 
  prepared_data:
  trained_model:
  predictions:
  score_report:
  deploy_flag:
jobs:
  hello_job:
    command: echo "hello" && echo "world" > ${{outputs.world_output}}/world.txt
    environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
    compute: azureml:test
    outputs:
      world_output:
  world_job:
    command: cat ${{inputs.world_input}}/world.txt
    environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu:23
    compute: azureml:test
    inputs:
      world_input: ${{parent.jobs.hello_job.outputs.world_output}}
