name: create-compute

on: 
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      size:  
        required: true
        type: number
      min_instances: 
        required: true
        type: number
      max_instances: 
        required: true
        type: number
      cluster_tier:
        required: true
        type: string
      resource_group:   
        required: true
        type: string
      workspace_name:  
        required: true
        type: string
jobs:
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: az ml compute create --name ${{ inputs.cluster_name }} \
                                  --type amlcompute \
                                  --size ${{ inputs.size }} \
                                  --min-instances ${{ inputs.min_instances }} \
                                  --max-instances ${{ inputs.max_instances }} \
                                  --tier ${{ inputs.cluster_tier }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace }}
  
