name: create-compute

on: 
  workflow_call:
    inputs:
      cluster_name:
        description: 'Cluster name'     
        required: true
        type: string
      size:
        description: 'size'     
        required: true
        type: number
      min_instances:
        description: 'min_instances'     
        required: true
        type: number
      max_instances:
        description: 'max_instances'     
        required: true
        type: number
      cluster_tier:
        description: 'cluster_tier'     
        required: true
        type: string
jobs:
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{inputs.cluster_name}} ${{inputs.size}} ${{inputs.min_instances}} ${{inputs.max_instances}} ${{inputs.cluster_tier}} 
  
