# This is a basic workflow to help you get started with Actions

name: create-compute

# Controls when the workflow will run
on: 
  workflow_call:
    inputs:
      cluster_name:
        description: 'Cluster name'     
        required: true
        type: string
      size:
        description: 'size'     
        required: true
        type: number
      min_instances:
        description: 'min_instances'     
        required: true
        type: number
      max_instances:
        description: 'max_instances'     
        required: true
        type: number
      cluster_tier:
        description: 'cluster_tier'     
        required: true
        type: string
    secrets:
      creds:
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      - name: install-extension
        uses: ./.github/workflows/install-aml-cli.yml
  
