name: create-compute-external

on: 
  workflow_dispatch:
jobs:
    run-compute-test:
      uses: timwferro/TestExternalAction/.github/workflows/create-compute.yml
      with:
        cluster_name: test
        size: Standard_D1_v2
        min_instances: 1
        max_instances: 1
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
