name: deploy-model-training-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
    runs-on: ubuntu-latest
    outputs:
      resource_group: ${{  steps.config-data.outputs.resource_group }}
      aml_workspace: ${{  steps.config-data.outputs.aml_workspace }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Read test
      uses: ./ # Uses an action in the root directory
      id: config-data
      with:
        config: ${{ github.workspace }}/files/config-infra-prod-test.yml
    - name: Echo step output
      run: echo " Loaded config! \n Resource Group ${{  steps.config-data.outputs.resource_group }} \n AML Workspace ${{  steps.config-data.outputs.aml_workspace }}\n"
  register-environment:
      needs: get-config
      uses: ./.github/workflows/register-environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file:  train-env.yml
        conda_file: train-conda.yml
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
  run-pipeline:
      needs: [get-config,register-environment]
      uses: ./.github/workflows/run-pipeline.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        parameters-file:  pipeline_train.yml
        job-name: test
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
