name: deploy-batch-endpoint-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: timwferro/TestExternalAction/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod-test.yml
  create-compute:
      needs: get-config
      uses: ./.github/workflows/create-compute.yml
      with:
        cluster_name: batch-cluster
        size: STANDARD_DS3_V2
        min_instances: 0
        max_instances: 5
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
  create-endpoint:
      needs: [get-config,create-compute]
      uses: ./.github/workflows/create-endpoint.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: batch-endpoint.yml
        endpoint_name: eptest
        endpoint_type: batch
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  create-deployment:
      uses: ./.github/workflows/create-deployment.yml
      needs: [get-config,create-endpoint]
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: batch-deployment.yml
        endpoint_name: eptest
        endpoint_type: batch
        deployment_name: eptestdeploy
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
