name: deploy-batch-endpoint-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: timwferro/TestExternalAction/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod-test.yml
  create-compute:
      needs: get-config
      uses: ./.github/workflows/create-compute.yml
      with:
        cluster_name: gpu-cluster
        size: Standard_NC6
        min_instances: 0
        max_instances: 1
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
  register-environment:
      needs: [get-config,register-environment]
      uses: ./.github/workflows/register_environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file: train-env-cv.yaml 
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  register-dataset:
      uses: ./.github/workflows/register-dataset.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        data_file: create_stanford_dogs_dataset.yaml
        name: stanford_dogs
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  run-pipeline:
      needs: [get-config,register-environment]
      uses: ./.github/workflows/run-pipeline.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        parameters-file:  pipeline-cv.yml
        job-name: cv-train
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
