name: create-compute-test

on: 
  workflow_dispatch:
jobs:
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds:  ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-compute
        id: test
        run: |
          echo "::set-output name=test::$(az ml model list --resource-group DJMiscRG --workspace-name DemoMLWorkspace | jq .location)"
      - name: output
        run: |
          echo ${{ steps.test.outputs.test }}
