name: workflow-test

on: 
  workflow_dispatch:
jobs:
    run-compute-test:
      uses: ./.github/workflows/create-compute.yml
      with:
        cluster_name: test
        size: Standard_D1_v2
        min_instances: 1
        max_instances: 1
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    run-environment-test:
      uses: ./.github/workflows/register-environment.yml
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
        environment_file: environment.yml
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
