name: read-yaml-external
on: 
  workflow_dispatch:
jobs:
    get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@GHA-read-vulnerability-update
      with:
        file_name: files/config-infra-prod-test.yml
    register-environment:
      needs: get-config
      runs-on: ubuntu-latest
      steps:
        - name: test-output
          run: |
            echo  ${{ format('{0}-eptest', needs.get-config.outputs.resource_group) }}
        
        
        
