name: read-yaml-external
on: 
  workflow_dispatch:
jobs:
    read-external-test:
      uses:  Azure/mlops-templates/.github/workflows/read-yaml.yml@GHA-testing-jul31
      with:
        file_name: files/config-infra-prod-test.yml
        
        
