name: read-yaml-external
on: 
  workflow_dispatch:
jobs:
    read-external-test:
      uses: timwferro/TestExternalAction/.github/workflows/read-yaml.yml@main
      with:
        file_name: files/config-infra-prod-test.yml
        
        
