name: register-dataset

on: 
  workflow_call:
    inputs:
      environment_file:
        required: true
        type: string
    secrets:
      creds:
        required: true
jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true 
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-compute
        run: az ml environment create --file ${{ inputs.environment_file }}
  
