name: test-dataset-external

on: 
  workflow_dispatch:
jobs:
    run-dataset-test:
      uses: timwferro/TestExternalAction/.github/workflows/register-dataset.yml@main
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
        data_file: data.yml
        name: demo_test
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
