name: test-run-pipeline-external

on: 
  workflow_dispatch:
jobs:
    run-dataset-test:
      uses: timwferro/TestExternalAction/.github/workflows/run-pipeline.yml@main
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
        parameters-file: pipeline.yml
        job-name: demo_test
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
