name: test-create-compute-external

on: 
  workflow_dispatch:
jobs:
    run-compute-test:
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
      with:
        cluster_name: test
        size: Standard_D1_v2
        min_instances: 1
        max_instances: 1
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
