name: workflow-test

on: 
  workflow_dispatch:
jobs:
    run-environment-test:
      uses: ./.github/workflows/connect-to-workspace.yml
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
