name: test-register-environment-external

on: 
  workflow_dispatch:
jobs:
    run-environment-test:
      uses: Azure/mlops-templates/.github/workflows/register-environment.yml@gha-nlp
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
        environment_file: files/train-nlp.yml
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
        
        
