name: dataset-only-test

on: 
  workflow_dispatch:
jobs:
    run-dataset-test:
      uses: ./.github/workflows/run-pipeline.yml
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
        parameters-file: data.yml
        job-name: demo_test
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
