name: test-create-deployment-external

on: 
  workflow_dispatch:
jobs:
    run-deployment-test:
      uses: timwferro/TestExternalAction/.github/workflows/create-deployment.yml@main
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
        endpoint_file: deployment.yml
        endpoint_name: eptest
        endpoint_type: batch
        deployment_name: eptestdeploy
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
