name: test-endpoint-external

on: 
  workflow_dispatch:
jobs:
    run-endpoint-test:
      uses: timwferro/TestExternalAction/.github/workflows/create-endpoint.yml@main
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
        endpoint_file: endpoint.yml
        endpoint_name: eptest
        endpoint_type: batch
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
