name: workflow-test-2

on: 
  workflow_dispatch:
jobs:
    run-workflow-test-2:
      uses: timwferro/TestExternalAction/.github/workflows/list-aml-workspace.yml@main
      with:
        resourceGroup: DJMiscRG
        workspace: DemoMLWorkspace
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
