name: workflow-test-external

on: 
  workflow_dispatch:
jobs:
    run-workflow-test-2:
      uses: timwferro/TestExternalAction/.github/workflows/create-endpoint.yml@main
      with:
        resource_group: DJMiscRG
        workspace_name: DemoMLWorkspace
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
