name: workflow-test-2

on: 
  workflow_dispatch:
jobs:
    run-workflow-test-2:
      uses: ./.github/workflows/connect-to-workspace.yml
      with:
        resourceGroup: DJMiscRG
        workspace: DemoMLWorkspace
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
